var authorizationValue =
  "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2MzY2MTIyMDMsImp0aSI6IitIdkU4TFNWdVNnZjAzOGREVVQ5RFNUY2pnQnJkTzMrR1BKSnFWak8zNDQ9IiwibmJmIjoxNjM2NjEyMjAzLCJleHAiOjE2MzY2ODQyMDMsImRhdGEiOnsidXNlcm5hbWUiOiJ0ZXN0c2FsZXMiLCJhY2NvdW50SWQiOiIzIn19.mfv77vzk_gmwbameFErAyjD53rNtlHf8d3gAMsh44b-foSBL_zgdc6qqBeOW12MJzj9O4dyxYiuEIVYfoxoOEA";

export default authorizationValue;
